//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v12.0.9.0 (NJsonSchema v9.13.10.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

namespace Tradeio.Stellar.Withdrawal.Controllers
{
    #pragma warning disable

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "12.0.9.0 (NJsonSchema v9.13.10.0 (Newtonsoft.Json v11.0.0.0))")]
    public interface IWithdrawalsController
    {
        /// <summary>Create withdrawal request</summary>
        /// <param name="traderId">Trader identifier</param>
        /// <param name="address">Withdrawal address</param>
        /// <param name="amount">Withdrawal amount</param>
        /// <returns>Create withdrawal request</returns>
        System.Threading.Tasks.Task<WithdrawalRequestModel> CreateWithdrawalRequestAsync(long traderId, string address, decimal amount);
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "12.0.9.0 (NJsonSchema v9.13.10.0 (Newtonsoft.Json v11.0.0.0))")]
    public partial class WithdrawalsController : Microsoft.AspNetCore.Mvc.Controller
    {
        private IWithdrawalsController _implementation;
    
        public WithdrawalsController(IWithdrawalsController implementation)
        {
            _implementation = implementation;
        }
    
        /// <summary>Create withdrawal request</summary>
        /// <param name="traderId">Trader identifier</param>
        /// <param name="address">Withdrawal address</param>
        /// <param name="amount">Withdrawal amount</param>
        /// <returns>Create withdrawal request</returns>
        [Microsoft.AspNetCore.Mvc.HttpPut, Microsoft.AspNetCore.Mvc.Route("v1/withdrawal")]
        public System.Threading.Tasks.Task<WithdrawalRequestModel> CreateWithdrawalRequest(long traderId, string address, decimal amount)
        {
            return _implementation.CreateWithdrawalRequestAsync(traderId, address, amount);
        }
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "12.0.9.0 (NJsonSchema v9.13.10.0 (Newtonsoft.Json v11.0.0.0))")]
    public interface IStatusController
    {
        /// <summary>Get service status</summary>
        /// <returns>Status</returns>
        System.Threading.Tasks.Task<Status> GetAsync();
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "12.0.9.0 (NJsonSchema v9.13.10.0 (Newtonsoft.Json v11.0.0.0))")]
    public partial class StatusController : Microsoft.AspNetCore.Mvc.Controller
    {
        private IStatusController _implementation;
    
        public StatusController(IStatusController implementation)
        {
            _implementation = implementation;
        }
    
        /// <summary>Get service status</summary>
        /// <returns>Status</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("v1/status")]
        public System.Threading.Tasks.Task<Status> Get()
        {
            return _implementation.GetAsync();
        }
    
    }
    
    

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.13.10.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class WithdrawalRequestModel 
    {
        [Newtonsoft.Json.JsonProperty("TraderId", Required = Newtonsoft.Json.Required.Always)]
        public long TraderId { get; set; }
    
        [Newtonsoft.Json.JsonProperty("Address", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Address { get; set; }
    
        [Newtonsoft.Json.JsonProperty("Amount", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public decimal? Amount { get; set; }
    
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.13.10.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class Status 
    {
        [Newtonsoft.Json.JsonProperty("environment", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Environment { get; set; }
    
        [Newtonsoft.Json.JsonProperty("version", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Version { get; set; }
    
        [Newtonsoft.Json.JsonProperty("current", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public long? Current { get; set; }
    
    
    }

    #pragma warning restore
}