//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v11.20.1.0 (NJsonSchema v9.11.0.0 (Newtonsoft.Json v9.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

namespace Tradeio.Stellar.Deposit.Controllers
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "11.20.1.0 (NJsonSchema v9.11.0.0 (Newtonsoft.Json v9.0.0.0))")]
    public interface IDepositsController
    {
        /// <summary>Get trader deposit address</summary>
        /// <param name="traderId">Trader identifier</param>
        /// <returns>Generates new trader deposit address</returns>
        System.Threading.Tasks.Task<DepositAddressModel> GetTraderAddressAsync(long traderId);
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "11.20.1.0 (NJsonSchema v9.11.0.0 (Newtonsoft.Json v9.0.0.0))")]
    public partial class DepositsController : Microsoft.AspNetCore.Mvc.Controller
    {
        private IDepositsController _implementation;
    
        public DepositsController(IDepositsController implementation)
        {
            _implementation = implementation;
        }
    
        /// <summary>Get trader deposit address</summary>
        /// <param name="traderId">Trader identifier</param>
        /// <returns>Generates new trader deposit address</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("v1/deposit/trader/address")]
        public System.Threading.Tasks.Task<DepositAddressModel> GetTraderAddress(long traderId)
        {
            return _implementation.GetTraderAddressAsync(traderId);
        }
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "11.20.1.0 (NJsonSchema v9.11.0.0 (Newtonsoft.Json v9.0.0.0))")]
    public interface IStatusController
    {
        /// <summary>Get service status</summary>
        /// <returns>Status</returns>
        System.Threading.Tasks.Task<Status> GetAsync();
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "11.20.1.0 (NJsonSchema v9.11.0.0 (Newtonsoft.Json v9.0.0.0))")]
    public partial class StatusController : Microsoft.AspNetCore.Mvc.Controller
    {
        private IStatusController _implementation;
    
        public StatusController(IStatusController implementation)
        {
            _implementation = implementation;
        }
    
        /// <summary>Get service status</summary>
        /// <returns>Status</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("v1/status")]
        public System.Threading.Tasks.Task<Status> Get()
        {
            return _implementation.GetAsync();
        }
    
    }
    
    

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.11.0.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class DepositAddressModel 
    {
        [Newtonsoft.Json.JsonProperty("TraderId", Required = Newtonsoft.Json.Required.Always)]
        public long TraderId { get; set; }
    
        [Newtonsoft.Json.JsonProperty("Address", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Address { get; set; }
    
        [Newtonsoft.Json.JsonProperty("CustomerId", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string CustomerId { get; set; }
    
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.11.0.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class Status 
    {
        [Newtonsoft.Json.JsonProperty("environment", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Environment { get; set; }
    
        [Newtonsoft.Json.JsonProperty("version", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Version { get; set; }
    
        [Newtonsoft.Json.JsonProperty("current", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public long? Current { get; set; }
    
    
    }

}